services:
  postgres:
    image: postgres:17
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - '60232:5432'
    environment:
      POSTGRES_USER: secrethome
      POSTGRES_PASSWORD: secrethome
      POSTGRES_DB: secrethome
      TZ: Asia/Tokyo
